- name: Create Compute Engine instances
  hosts: localhost
  gather_facts: no
  vars:
    gcp_project: m7shekhawat
    gcp_cred_kind: serviceaccount
    gcp_cred_file: "/Users/I566958/Downloads/m7shekhawat-68c582fc0945.json"
    zone: "asia-east1-b"
    region: "asia-east1"
    machine_type: "e2-medium"
    image: "projects/centos-cloud/global/images/centos-7-v20230203"
    disk_size: 100
    disk_type: "pd-ssd"

  tasks:
    - name: Create private IP for VM
      gcp_compute_address:
        name: "{{ zone }}-ip"
        region: "{{ region }}"
        project: "{{ gcp_project }}"
        service_account_file: "{{ gcp_cred_file }}"
        auth_kind: "{{ gcp_cred_kind }}"
      register: gce_ip
    - name: Create VM
      gcp_compute_instance:
        name: "{{ zone }}"
        machine_type: "{{ machine_type }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "{{ image }}"
              disk_type: "{{ disk_type }}"
              disk_size_gb: "{{ disk_size }}"
        network_interfaces:
          - access_configs:
              - name: External NAT  # public IP
                nat_ip: "{{ gce_ip }}"
                type: ONE_TO_ONE_NAT
        tags:
          items:
            - mysql-server
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        service_account_file: "{{ gcp_cred_file }}"
        auth_kind: "{{ gcp_cred_kind }}"
      register: gce

  post_tasks:
    - name: Wait for SSH for instance
      wait_for: delay=5 sleep=5 host={{ gce_ip.address }} port=22 state=started timeout=100
    - name: Save host data for first zone
      add_host: hostname={{ gce_ip.address }} groupname=gce_instances_ips


#- name: Create user group to VM
#  hosts: gce_instances_ips
#  gather_facts: no
#  tasks:
#  - name: Create ansible group
#    group:
#      name: ansible
#      state: present
#  - name: Create ansible user
#    user:
#      name: ansible
#      group: ansible
#  - name: Give sudo access to devops user
#    blockinfile:
#      path: /etc/sudoers
#      insertafter: 'root    ALL=(ALL)       ALL'
#      block: |
#        # Gives sudo access to the ansible group
#        %ansible        ALL=(ALL)       NOPASSWD: ALL

- name: Update packages and install mysql
  gather_facts: no
  hosts: gce_instances_ips
  become: yes   # to run as root
  become_method: sudo
  roles:
    - mysql